# Generated by Django 2.0.7 on 2019-07-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manhattan',
            name='APARTMENT_NUMBER',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='manhattan',
            name='EASE_MENT',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
