# Generated by Django 2.0.7 on 2019-07-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190702_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manhattan',
            name='LAND_SQUARE_FEET',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
